# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc877428418d8d4e05be96cff5ad116ac8c11331bef015881e20acee3ee3f533b57d04fc72f27f7efb925527aa5382c2448a1462c913ae86e744bf5d7366db1

test:
  secret_key_base: 6c7dc06d59f12bc791f4e861fec659ec25563e736de10f8fe6fec3365f5b74852a703e40957d70fd9b55fc6000da66ef65f55de36e41051d05b045207a18508c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
